### ISSUE TITLE
simstore_and_cli will need to be updated for OpenMM >= 7.6

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/mini-tutorials#4]
Following on https://github.com/openpathsampling/mini-tutorials/pull/2#issuecomment-909102232 (and summarizing some earlier comments in that thread):

1. The `simstore_and_cli` tutorial gets units as `from simtk import unit`.
2. Starting in OpenMM 7.6, that issues a warning. The correct import is now `from openmm import unit`.
3. For OpenMM < 7.6, `from openmm import unit` raises an error.

So our solution is to wait until there's widespread adoption of OpenMM 7.6, and at that point we'll update the tutorial. OpenMM 7.6 was released on August 27, 2021. I'm not sure at what point we expect "widespread adoption" --  maybe 3-6 months after release?

**Comment by sroet** [comment]
> I'm not sure at what point we expect "widespread adoption" -- maybe 3-6 months after release?

Maybe do it together with the default "January copyright cleanup" (I assume you have a similar effort in January updating copyright years in docs/websites/etc)? (So my vote would be early 2022)

**Comment by dwhswenson** [comment]
> Maybe do it together with the default "January copyright cleanup" (I assume you have a similar effort in January updating copyright years in docs/websites/etc)? (So my vote would be early 2022)

Here it is! @sroet opened PRs for annual copyright updates on various projects today; I remembered that there had been a comment *somewhere* about something else to do at the same time. This was it.

For tutorials like these I'm in favor of shorter periods of supporting old versions (so we can make this change any time now). For the actual underlying libraries, we try to apply [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) practices for NumPy to all requirements, which means continuing support for at least 24 months after release.
